# This ansible playbook will deploy the python app
# Ref: https://docs.ansible.com/ansible/latest/collections/community/docker/docker_image_module.html#parameter-source
# Ref: https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
- name: Application deployment
  hosts: ec2_vm
  become: true
  vars:
    appname: "chuck_norris_app"
  tasks:
    - name: Copy webapp files
      ansible.builtin.copy:
        src: ./webapp
        dest: /opt
        mode: preserve
    - name: Build webapp image
      community.docker.docker_image:
        name: "{{ appname }}"
        build:
          path: /opt/webapp
          dockerfile: Dockerfile
          # args:
            # log_volume: /var/log/myapp
            # listen_port: 8080
        source: build

    - name: "Start {{ appname }}"
      community.docker.docker_container:
        name: chuck-container
        image: "{{ appname }}"
        published_ports:
          - 0.0.0.0:5000:5000
          # TODO: fix ipv6 expose port
          # - "[::/0]"":5000:5000
        state: started

    - name: Install nginx config
      ansible.builtin.copy:
        src: proxy.conf
        dest: /etc/nginx/sites-available/default
        mode: preserve
      notify:
        - Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
